name: tagseq
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  # Core tools
  - perl >=5.26
  - python >=3.8
  - make
  # NGS tools
  - star >=2.7
  - adapterremoval >=2.3
  - fastqc >=0.11
  - samtools >=1.9
  - bedtools >=2.29
  - picard >=2.20
  - umi_tools >=1.0
  - emboss >=6.6   # provides water
  - bedops >=2.4
  - ucsc-bedgraphtobigwig >=377
  # Python packages
  - svgwrite
